Repository vtex-apps/store-components, pull requests merged in 2018-12, with the labels that each got.

#219 Fix negative padding on Slider arrows.
  CHANGELOG.md
  manifest.json
  react/components/Slider/global.css
Labels: bug

#220 Make Logo properly receive width and height properties.
  CHANGELOG.md
  manifest.json
  react/components/Logo/index.js
Labels: bug

#225 Fix DiscountBadge conditional div root
  CHANGELOG.md
  manifest.json
  react/components/DiscountBadge/index.js
Labels: bug

#227 Feature/toast
  CHANGELOG.md
  manifest.json
  react/components/BuyButton/index.js
Labels: enhancement

#228 Add CSS modules to ProductName
  CHANGELOG.md
  manifest.json
  react/components/ProductName/index.js
  react/components/ProductName/productName.css
Labels: breaking-change, enhancement

#229 Fix Shipping Simulator Price Table Number Format
  CHANGELOG.md
  react/components/ShippingSimulator/components/ShippingTableRow.js
Labels: bug

#232 Support to messages builder
  CHANGELOG.md
  manifest.json
  messages/en-US.json
  messages/es-AR.json
  messages/pt-BR.json
Labels: enhancement
