Repository vtex-apps/store-components, pull requests merged in 2019-10, with the labels that each got.

#591 Prevent DiscountBadge from rendering with negative discount values
  CHANGELOG.md
  react/components/DiscountBadge/index.js
Labels: bug

#605 Add heightImg and widthImg props to the SKUSelector
  CHANGELOG.md
  manifest.json
  react/__mocks__/vtex.responsive-values/index.js
  react/components/SKUSelector/Wrapper.tsx
  react/components/SKUSelector/components/SKUSelector.tsx
  react/components/SKUSelector/components/SelectorItem.tsx
  react/components/SKUSelector/components/Variation.tsx
  react/components/SKUSelector/index.tsx
  react/components/SKUSelector/utils/index.ts
  react/typings/vtex.responsive-values.d.ts
  react/yarn.lock
  yarn.lock
Labels: bug, enhancement

#606 Update CSS handles on multiple components
  .eslintrc
  CHANGELOG.md
  docs/InfoCard.md
  docs/ProductDescription.md
  manifest.json
  package.json
  react/__mocks__/vtex.css-handles.js
  react/__tests__/components/__snapshots__/ProductDescription.test.js.snap
  react/__tests__/components/__snapshots__/ProductSpecifications.test.js.snap
  react/__tests__/components/__snapshots__/SearchBar.test.js.snap
  react/components/InfoCard/CallToAction.js
  react/components/InfoCard/index.js
  react/components/InfoCard/infoCard.css
  react/components/Logo/index.js
  react/components/Logo/styles.css
  react/components/Newsletter/index.js
  react/components/Newsletter/style.css
  react/components/ProductBrand/index.js
  react/components/ProductBrand/productBrand.css
  react/components/ProductDescription/index.js
  react/components/ProductDescription/styles.css
  react/components/ProductName/Wrapper.js
  react/components/ProductName/index.js
  react/components/ProductName/productName.css
  react/components/ProductSpecifications/index.js
  react/components/ProductSpecifications/styles.css
  react/components/SearchBar/components/AutocompleteInput.js
  react/components/SearchBar/components/ResultsList.js
  react/components/SearchBar/components/SearchBar.js
  react/components/SearchBar/index.js
  react/components/SearchBar/styles.css
  react/package.json
  react/yarn.lock
  yarn.lock
Labels: enhancement

#615 Fix infinite loop in SKUSelector
  CHANGELOG.md
  react/components/SKUSelector/index.tsx
Labels: bug

#613 Fix SearchBar make a request everytime you type something
  CHANGELOG.md
  react/components/SearchBar/components/SearchBar.js
  react/components/SearchBar/index.js
Labels: bug
